# Generated by Django 3.2.20 on 2023-10-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231013_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='project_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
    ]
