# Generated by Django 3.2.20 on 2023-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='D:\\Projects\\probsolution\\probsolution\\media\\NoneImage.jpg', null=True, upload_to='posts/'),
        ),
    ]
